




CREATE          VIEW dbo.vw_DELTEK_EMPL_HireDate_before_010204
AS
SELECT     TOP 100 PERCENT dbo.DELTEK_EMPL.EMPL_ID, dbo.DELTEK_EMPL.ORIG_HIRE_DT, dbo.DELTEK_EMPL.ADJ_HIRE_DT, 
			dbo.IDMaster.IDMaster_DOE DOE,
                      dbo.DELTEK_EMPL.LAST_NAME, dbo.DELTEK_EMPL.FIRST_NAME, dbo.DELTEK_EMPL.PREF_NAME, dbo.DELTEK_EMPL_LAB_INFO.ORG_ID, 
                      dbo.DELTEK_EMPL_LAB_INFO.LAB_GRP_TYPE, dbo.DELTEK_EMPL.TS_PD_CD
FROM         dbo.DELTEK_EMPL INNER JOIN
                      dbo.DELTEK_EMPL_LAB_INFO ON dbo.DELTEK_EMPL.EMPL_ID = dbo.DELTEK_EMPL_LAB_INFO.EMPL_ID
			INNER JOIN dbo.IDMaster ON dbo.IDMaster.IDMaster_WestatID = dbo.DELTEK_EMPL.EMPL_ID
WHERE     (dbo.IDMaster.IDMaster_DOE < CONVERT(DATETIME, '2008-01-02 00:00:00', 102)) AND 
                      (dbo.DELTEK_EMPL_LAB_INFO.END_DT > CONVERT(DATETIME, '2078-12-30 00:00:00', 102)) 
			AND (dbo.DELTEK_EMPL.S_EMPL_STATUS_CD = 'ACT') 
                      AND (dbo.DELTEK_EMPL.EMPL_ID < '2000000') AND (dbo.DELTEK_EMPL.TS_PD_CD = 'SEMI') OR
                      (dbo.IDMaster.IDMaster_DOE < CONVERT(DATETIME, '2008-01-02 00:00:00', 102)) AND 
                      (dbo.DELTEK_EMPL_LAB_INFO.END_DT > CONVERT(DATETIME, '2078-12-30 00:00:00', 102)) AND 
				(dbo.DELTEK_EMPL.S_EMPL_STATUS_CD = 'ACT') 
                      AND (dbo.DELTEK_EMPL.EMPL_ID < '2000000') AND (dbo.DELTEK_EMPL_LAB_INFO.ORG_ID < '1.56.11')
				--and dbo.DELTEK_EMPL.EMPL_ID='1433078'
ORDER BY dbo.DELTEK_EMPL.LAST_NAME, dbo.DELTEK_EMPL.PREF_NAME





