CREATE VIEW dbo.vw_R_Deltek_Info
AS
SELECT dbo.DELTEK_EMPL.EMPL_ID, 
    dbo.DELTEK_EMPL.LAST_NAME, 
    dbo.DELTEK_EMPL.FIRST_NAME, 
    dbo.DELTEK_EMPL.TERM_DT, 
    dbo.DELTEK_EMPL_LAB_INFO.ORG_ID, 
    dbo.DELTEK_EMPL_LAB_INFO.END_DT
FROM dbo.DELTEK_EMPL INNER JOIN
    dbo.DELTEK_EMPL_LAB_INFO ON 
    dbo.DELTEK_EMPL.EMPL_ID = dbo.DELTEK_EMPL_LAB_INFO.EMPL_ID
     RIGHT OUTER JOIN
    dbo.CRS_tblEmpl_Info ON 
    dbo.DELTEK_EMPL.EMPL_ID = dbo.CRS_tblEmpl_Info.Empl_ID
WHERE (dbo.DELTEK_EMPL_LAB_INFO.END_DT > CONVERT(DATETIME,
     '2078-12-30 00:00:00', 102))
