CREATE VIEW dbo.vw_Sum_HrsByEmpl_FY2003
AS
SELECT     TOP 100 PERCENT EMPL_ID, SUM(ACT_HRS) AS SumActHrs
FROM         dbo.DELTEK_LAB_HS
WHERE     (FY_CD = '2003') AND (PD_NO < 12) AND (LEFT(PROJ_ID, 4) <> '1196')
GROUP BY EMPL_ID
ORDER BY SUM(ACT_HRS) DESC
