CREATE TABLE [dbo].[DELTEK_EMPL] (
    [EMPL_ID]           VARCHAR (12)    NOT NULL,
    [LV_PD_CD]          VARCHAR (4)     NULL,
    [TAXBLE_ENTITY_ID]  VARCHAR (10)    NULL,
    [SSN_ID]            VARCHAR (11)    NOT NULL,
    [ORIG_HIRE_DT]      DATETIME        NOT NULL,
    [ADJ_HIRE_DT]       DATETIME        NULL,
    [TERM_DT]           DATETIME        NULL,
    [S_EMPL_STATUS_CD]  VARCHAR (3)     NOT NULL,
    [UNIT_AMT]          NUMERIC (10, 4) NOT NULL,
    [SPVSR_NAME]        VARCHAR (25)    NOT NULL,
    [LAST_NAME]         VARCHAR (25)    NOT NULL,
    [FIRST_NAME]        VARCHAR (20)    NOT NULL,
    [MID_NAME]          VARCHAR (10)    NOT NULL,
    [PREF_NAME]         VARCHAR (10)    NOT NULL,
    [NAME_PRFX_CD]      VARCHAR (6)     NOT NULL,
    [NAME_SFX_CD]       VARCHAR (6)     NOT NULL,
    [NOTES]             VARCHAR (254)   NOT NULL,
    [TS_PD_CD]          VARCHAR (4)     NOT NULL,
    [BIRTH_DT]          DATETIME        NULL,
    [CITY_NAME]         VARCHAR (25)    NOT NULL,
    [COUNTRY_CD]        VARCHAR (8)     NULL,
    [LAST_FIRST_NAME]   VARCHAR (25)    NOT NULL,
    [LN_1_ADR]          VARCHAR (30)    NOT NULL,
    [LN_2_ADR]          VARCHAR (30)    NOT NULL,
    [LN_3_ADR]          VARCHAR (30)    NOT NULL,
    [MAIL_STATE_DC]     VARCHAR (15)    NULL,
    [POSTAL_CD]         VARCHAR (10)    NOT NULL,
    [MODIFIED_BY]       VARCHAR (20)    NOT NULL,
    [TIME_STAMP]        DATETIME        NOT NULL,
    [LOCATOR_CD]        VARCHAR (6)     NOT NULL,
    [PRIR_NAME]         VARCHAR (25)    NOT NULL,
    [COMPANY_ID]        VARCHAR (10)    NOT NULL,
    [LAST_REVIEW_DT]    DATETIME        NULL,
    [NEXT_REVIEW_DT]    DATETIME        NULL,
    [SEX_CD]            VARCHAR (1)     NULL,
    [MARITAL_CD]        VARCHAR (1)     NULL,
    [ELIG_AUTO_PAY_FL]  VARCHAR (1)     NOT NULL,
    [EMAIL_ID]          VARCHAR (60)    NOT NULL,
    [MGR_EMPL_ID]       VARCHAR (12)    NULL,
    [S_RACE_CD]         VARCHAR (10)    NOT NULL,
    [PR_SERV_EMPL_ID]   VARCHAR (12)    NOT NULL,
    [COUNTY_NAME]       VARCHAR (25)    NOT NULL,
    [TS_PD_REG_HRS_NO]  NUMERIC (5)     NOT NULL,
    [PAY_PD_REG_HRS_NO] NUMERIC (5)     NOT NULL,
    [DISABLED_FL]       VARCHAR (1)     NOT NULL,
    [MOS_REVIEW_NO]     NUMERIC (5)     NOT NULL,
    [CONT_NAME_1]       VARCHAR (25)    NOT NULL,
    [CONT_NAME_2]       VARCHAR (25)    NOT NULL,
    [CONT_PHONE_1]      VARCHAR (20)    NOT NULL,
    [CONT_PHONE_2]      VARCHAR (20)    NOT NULL,
    [CONT_REL_1]        VARCHAR (15)    NOT NULL,
    [CONT_REL_2]        VARCHAR (15)    NOT NULL,
    [UNION_EMPL_FL]     VARCHAR (1)     NOT NULL,
    [VISA_TYPE_CD]      VARCHAR (10)    NULL,
    [VET_STATUS_S]      VARCHAR (1)     NULL,
    [VET_STATUS_V]      VARCHAR (1)     NULL,
    [VET_STATUS_O]      VARCHAR (1)     NULL,
    [VET_STATUS_R]      VARCHAR (1)     NULL,
    [ESS_PIN_ID]        VARCHAR (120)   NULL,
    [PIN_UPDATED_FL]    VARCHAR (1)     NOT NULL,
    [S_ESS_COS_CD]      VARCHAR (2)     NULL,
    [HOME_EMAIL_ID]     VARCHAR (60)    NULL,
    [ROWVERSION]        NUMERIC (10)    NULL,
    [VET_RELEASE_DT]    DATETIME        NULL,
    [CONTRACTOR_FL]     VARCHAR (1)     NULL,
    [BLIND_FL]          VARCHAR (1)     NULL,
    [VISA_DT]           DATETIME        NULL,
    [VET_STATUS_D]      VARCHAR (1)     NULL,
    [VET_STATUS_A]      VARCHAR (1)     NULL,
    CONSTRAINT [PK_DELTEK_EMPL] PRIMARY KEY CLUSTERED ([EMPL_ID] ASC) WITH (FILLFACTOR = 90)
);

