CREATE TABLE [dbo].[PAY_TYPE] (
    [PAY_TYPE]           NVARCHAR (3)    NOT NULL,
    [PAY_TYPE_DESC]      VARCHAR (30)    NOT NULL,
    [PAY_TYPE_FCTR_QTY]  DECIMAL (5, 4)  NOT NULL,
    [PAY_TYPE_AMT]       DECIMAL (10, 4) NOT NULL,
    [S_PAY_TYPE_USE_CD]  VARCHAR (1)     NOT NULL,
    [APPLY_TO_EXMPT_FL]  VARCHAR (1)     NOT NULL,
    [CST_ONLY_FL]        VARCHAR (1)     NOT NULL,
    [S_INCL_WGT_AVG_CD]  VARCHAR (1)     NOT NULL,
    [ALLOW_RECAST_FL]    VARCHAR (1)     NOT NULL,
    [APPLY_SAL_EMPL_FL]  VARCHAR (1)     NOT NULL,
    [OT_PAY_TYPE_FL]     VARCHAR (1)     NOT NULL,
    [RECAST_PAY_TYPE]    VARCHAR (3)     NULL,
    [MODIFIED_BY]        VARCHAR (18)    NOT NULL,
    [TIME_STAMP]         DATETIME        NOT NULL,
    [APPLY_NON_EXMPT_FL] VARCHAR (1)     NOT NULL,
    [ROWVERSION]         DECIMAL (5)     NULL,
    [BEN_REIMB_FL]       VARCHAR (1)     NOT NULL
);

