//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCRS.CoreModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRChangeWorktime : HRTransaction
    {
        public Nullable<bool> IsFulltimer { get; set; }
        public Nullable<double> PartTimeRatio { get; set; }
        public Nullable<bool> IsFlexHours { get; set; }
        public Nullable<bool> IsReturnToFullTime { get; set; }
        public Nullable<bool> IsTelework { get; set; }
        public Nullable<bool> IsAWASubmitted { get; set; }
    }
}
