//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCRS.CoreModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRLaborReclassfication : HRTransaction
    {
        public string LaborClass { get; set; }
        public string LaborGroup { get; set; }
        public string GLC { get; set; }
    }
}
