//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCRS.CoreModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRTransactionHistory
    {
        public int id { get; set; }
        public Nullable<int> HRTransactionid { get; set; }
        public string reviewedBy { get; set; }
        public Nullable<System.DateTime> reviewedOn { get; set; }
        public Nullable<int> statusId { get; set; }
        public string reviewerNote { get; set; }
    
        public virtual HRTransaction HRTransaction { get; set; }
        public virtual HRTransactionStatus HRTransactionStatu { get; set; }
    }
}
