//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCRS.CoreModel
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class HRTransaction
    {
        public HRTransaction()
        {
            this.HRTransactionHistories = new HashSet<HRTransactionHistory>();
        }
    
        public int id { get; set; }
        public Nullable<int> statusId { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdFor { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public string note { get; set; }
        public int HRTransactionTypId { get; set; }
    
        public virtual ICollection<HRTransactionHistory> HRTransactionHistories { get; set; }
        public virtual HRTransactionStatus HRTransactionStatu { get; set; }
        public virtual HRTransactionType HRTransactionType { get; set; }
    }
}
