//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCRS.CoreModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xCRSContext : DbContext
    {
        public xCRSContext()
            : base("name=xCRSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HRTransactionHistory> HRTransactionHistories { get; set; }
        public DbSet<HRTransaction> HRTransactions { get; set; }
        public DbSet<HRTransactionStatus> HRTransactionStatus1 { get; set; }
        public DbSet<HRTransactionType> HRTransactionTypes { get; set; }
    }
}
