
CREATE       Procedure usp_Sum_HrsByEmpl_FY_HD_After_year 
	@pd_month as integer,
	@pd_year as varchar(4)
AS
/*
SELECT ORA_DKHS.EMPL_ID,  
SUM(ACT_HRS)/((DATEDIFF(d, CONVERT(DATETIME, '2006-1-1 00:00:00', 102), DK_LAB.ORIG_HIRE_DT) + 2) * 5 / 7 * 8) * 100 AS PercentFT 
FROM vw_DELTEK_EMPL_HireDate_after_010104 DK_LAB INNER JOIN
     cpprod..DELTEK.LAB_HS ORA_DKHS ON DK_LAB.EMPL_ID = ORA_DKHS.EMPL_ID
WHERE 
((DATEDIFF(d, DK_LAB.ORIG_HIRE_DT, CONVERT(DATETIME, '2006-1-1 00:00:00', 102)) + 2) * 5 / 7 * 8 > 0) AND
((ORA_DKHS.FY_CD = @pd_year) AND (ORA_DKHS.PD_NO <= @pd_month) AND (LEFT(ORA_DKHS.PROJ_ID, 4) <> '1196'))
GROUP BY ORA_DKHS.EMPL_ID, DK_LAB.ORIG_HIRE_DT
HAVING (ORA_DKHS.EMPL_ID IS NOT NULL)
ORDER BY SUM(ACT_HRS)/ ((DATEDIFF(d, CONVERT(DATETIME, 
                      '2006-1-1 00:00:00', 102), DK_LAB.ORIG_HIRE_DT) + 2) * 5 / 7 * 8) * 100 DESC

*/

SELECT ORA_DKHS.EMPL_ID,   
SUM(ACT_HRS)/((DATEDIFF(d, CONVERT(DATETIME, '2006-1-1 00:00:00', 102), DK_LAB.ORIG_HIRE_DT) + 2) * 5 / 7 * 8) * 100 AS PercentFT 
FROM vw_DELTEK_EMPL_HireDate_after_010104 DK_LAB INNER JOIN
     cpprod..DELTEK.LAB_HS ORA_DKHS ON DK_LAB.EMPL_ID = ORA_DKHS.EMPL_ID
WHERE 
((DATEDIFF(d, CONVERT(DATETIME, '2006-1-1 00:00:00', 102), DK_LAB.ORIG_HIRE_DT) + 2) * 5 / 7 * 8 > 0) AND
((ORA_DKHS.FY_CD = @pd_year) AND (ORA_DKHS.PD_NO <= @pd_month) AND (LEFT(ORA_DKHS.PROJ_ID, 4) <> '1196'))
GROUP BY ORA_DKHS.EMPL_ID, DK_LAB.ORIG_HIRE_DT
HAVING (ORA_DKHS.EMPL_ID IS NOT NULL)
ORDER BY SUM(ACT_HRS)/ ((DATEDIFF(d, DK_LAB.ORIG_HIRE_DT, CONVERT(DATETIME, 
                      '2006-1-1 00:00:00', 102)) + 2) * 5 / 7 * 8) * 100 DESC


