//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        public string WPN { get; set; }
        public short LastRoundNumber { get; set; }
        public string RFP_Number { get; set; }
        public string ProposalStatusCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
