//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalRound
    {
        public string WPN { get; set; }
        public short RoundNumber { get; set; }
        public string ContractTypeCode { get; set; }
        public string PMCode { get; set; }
        public string PECode { get; set; }
        public string PSCode { get; set; }
        public string IsWestatPrime { get; set; }
        public string WestatSubTo { get; set; }
        public string Subcontractors { get; set; }
        public string Consultants { get; set; }
        public string Vendors { get; set; }
        public string RoundTypeCode { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string PrimaryDeliveryModeCode { get; set; }
        public Nullable<System.DateTime> DeliveryConfirmedDate { get; set; }
        public string DuePlace { get; set; }
        public string SDBPartPlanRequired { get; set; }
        public string SBSubContractPlanRequired { get; set; }
        public string NAICS_SIC_Code { get; set; }
        public Nullable<decimal> BidAmount { get; set; }
        public Nullable<decimal> BidFeePercent { get; set; }
        public Nullable<decimal> RateDiscount { get; set; }
        public Nullable<decimal> SBPercentOfContract { get; set; }
        public Nullable<decimal> SBPercentOfOutsourcing { get; set; }
        public Nullable<System.DateTime> ExpectedContractStartDate { get; set; }
        public Nullable<System.DateTime> ExpectedContractEndDate { get; set; }
        public string RoundStatusCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdatedBy { get; set; }
        public string DueTime { get; set; }
    }
}
